"""empty message

Revision ID: 71bb09bb3395
Revises: 
Create Date: 2021-03-23 22:01:03.827733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bb09bb3395'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('noBedrooms', sa.Integer(), nullable=True),
    sa.Column('noBathrooms', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('photoFileName', sa.String(length=255), nullable=True),
    sa.Column('propertyType', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
